version: "2"
plugins:
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: '.eslint.json'
  duplication:
    enabled: true
    config:
      languages:
        - javascript
checks:
  method-lines:
    config:
      threshold: 40
exclude_patterns:
  - ".*.*"
  - "dist/**.js"
  - "gulp/**.js"
  - "test/**.js"
  - "test/fixtures/**.*"
  - "test/helpers/**.js"
  - "*.json"
  - ".gitignore"
  - "**.md"
  - "*.js"
  - "**.coffee"
  - "LICENSE"
