engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: '.eslint.json'
  duplication:
    enabled: false
    config:
      languages:
        - javascript
ratings:
   paths:
    - "lib/**.js"
exclude_paths:
  - "dist/**.js"
  - "gulp/**.js"
  - "test/**.js"
  - "test/fixtures/**.js"
  - "**.json"
  - "**.md"
  - "*.js"
  - "**.coffee"
  - "LICENSE"
