plugins:
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: '.eslint.json'
  duplication:
    enabled: false
    config:
      languages:
        - javascript
exclude_patterns:
  - "*.yml"
  - "dist/**.js"
  - "gulp/**.js"
  - "test/**.js"
  - "test/fixtures/**.js"
  - "*.json"
  - ".gitignore"
  - "**.md"
  - "*.js"
  - "**.coffee"
  - "LICENSE"
