language: node_js
sudo: false
addons:
  code_climate:
    repo_token: 'e7d897b341e458ed1c6fde47d4c1f314a237d9f83d7fa990dff7ba1c14147cea'
env:
  - CXX=g++-4.8
install:
  - "npm install"
script:
  - "npm run travis"
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
cache:
  directories:
    - 'node_modules'
