language: node_js
sudo: false
addons:
  code_climate:
    repo_token: 'TODO'
install:
  - "npm install npm -g"
  - "npm install"
script:
  - "gulp travis"
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
cache:
  directories:
    - 'node_modules'
